version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo

jobs:
  build_and_deploy:
    executor: docker-executor
    steps:
      - checkout
      
      - setup_remote_docker
      
      - run:
          name: Build Docker Image
          command: |
            docker build -t docker.io/${DOCKERHUB_USERNAME}/myservice:${CIRCLE_BUILD_NUM} ./microservice
      
      - run:
          name: Scan with Trivy
          command: |
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
            trivy image docker.io/${DOCKERHUB_USERNAME}/myservice:${CIRCLE_BUILD_NUM} || true
      
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      
      - run:
          name: Push Docker Image
          command: |
            docker push docker.io/${DOCKERHUB_USERNAME}/myservice:${CIRCLE_BUILD_NUM}
      
      - run:
          name: Update Helm Chart
          command: |
            sed -i "s/tag:.*/tag: ${CIRCLE_BUILD_NUM}/" helm-chart/myservice/values.yaml
            git config --global user.email "circleci@ci"
            git config --global user.name "circleci"
            git add helm-chart/myservice/values.yaml
            git commit -m "Update image tag to ${CIRCLE_BUILD_NUM}" || echo "No changes to commit"
            git push https://$GITHUB_TOKEN@github.com/Highshow14/Microservice.git main || echo "Push failed"
      
workflows:
  version: 2
  build_and_deploy_workflow:
    jobs:
      - build_and_deploy
