apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-creds
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgB...  # This should be encrypted using kubeseal
  template:
    type: kubernetes.io/dockerconfigjson
    metadata:
      name: dockerhub-creds
      namespace: default
