pipeline {
  agent any
  environment {
    IMAGE = "docker.io/Highshow14/myservice:${BUILD_NUMBER}"
  }
  stages {
    stage('Build') {
      steps {
        sh 'docker build -t $IMAGE ./microservice'
      }
    }
    stage('Scan with Trivy') {
      steps {
        sh 'trivy image $IMAGE || true'
      }
    }
    stage('Push to Docker Hub') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
          sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
          sh 'docker push $IMAGE'
        }
      }
    }
    stage('Update Helm Chart & Push to GitHub') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'github-creds', passwordVariable: 'GIT_PASS', usernameVariable: 'GIT_USER')]) {
          sh '''
            git config --global user.email "jenkins@ci"
            git config --global user.name "jenkins"
            git clone https://$GIT_USER:$GIT_PASS@github.com/Highshow14/Microservice.git repo
            cd repo
            sed -i "s/tag:.*/tag: ${BUILD_NUMBER}/" helm-chart/myservice/values.yaml
            git add helm-chart/myservice/values.yaml
            git commit -m "Update image tag to ${BUILD_NUMBER}"
            git push origin main
          '''
        }
      }
    }
  }
}
